// Custom Matrix state event types for Tamarix
export const TAMARIX_EVENT_TYPES = {
  TASK_STATUS: "com.tamarix.task_status",
  PRIORITY: "com.tamarix.priority",
  DUE_DATE: "com.tamarix.due_date",
  TASK_TYPE: "com.tamarix.task_type",
  ESTIMATE: "com.tamarix.estimate",
  TAGS: "com.tamarix.tags",
  TICKET_ID: "com.tamarix.ticket_id",
  RELATION: "com.tamarix.relation",
  SPRINT_META: "com.tamarix.sprint_meta",
  ASSIGNEE: "com.tamarix.assignee",
  TASK_ARCHIVED: "com.tamarix.task_archived",
  DESCRIPTION: "com.tamarix.description",
  WORKLOG: "com.tamarix.worklog",
  VERSION: "com.tamarix.version",
  TASK_VERSION: "com.tamarix.task_version",
  TASK_TEMPLATE: "com.tamarix.task_template",
  CUSTOM_FIELD: "com.tamarix.custom_field",
  CUSTOM_FIELD_VALUE: "com.tamarix.custom_field_value",
  APPROVAL: "com.tamarix.approval",
  APPROVAL_CONFIG: "com.tamarix.approval_config",
  SORT_ORDER: "com.tamarix.sort_order",
  EXTERNAL_LINK: "com.tamarix.external_link",
  GIT_CONFIG: "com.tamarix.git_config",
  INTEGRATION: "com.tamarix.integration",
  INTEGRATION_EVENT: "com.tamarix.integration_event",
  WATCHER: "com.tamarix.watcher",
  NOTIFICATION_PREFS: "com.tamarix.notification_prefs"
} as const;
